### ISSUE TITLE
Prevent user from dismissing toast

### ISSUE THREAD

**Issue by AshotN** [calintamas/react-native-toast-message#246] opened 2021-09-19 19:28 UTC
Is there currently any means for the user not to be able to dismiss the notification?

**Comment by dederomagnolo** [comment] 2021-09-25 20:05
I'm looking for this feature too. Any ideas?

**Comment by calintamas** [comment] 2021-10-21 11:18
Closing as duplicate of https://github.com/calintamas/react-native-toast-message/issues/154. Let's move the discussion there

**Closed by calintamas** 2021-10-21 11:18 UTC
Labels: duplicate, enhancement
